# tell docker what version of the docker-compose.yml were using
version: '2'

# start the services section
services:
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/yao3060/nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8080:80"
    links:
      - php-fpm:php
    tty: true
    volumes:
      - ./app:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx

  php-fpm:
    image: registry.cn-hangzhou.aliyuncs.com/yao3060/php
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
    tty: true
    links:
      - 'mysql:mysql'
    volumes:
      - ./app:/var/www

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: domain
      MYSQL_ROOT_PASSWORD: root
    restart: always

  rabbitmq:
    image: rabbitmq:management-alpine
    restart: always
    ports:
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin