#!/usr/bin/env bash

startup () {
    docker-compose up -d
}

create () {
    startup
    # post-up stuff
    DB_CONTAINER_ID=`docker ps -q -f NAME=mysql`

    echo "Waiting for MySQL server to enter a state of readiness..."
    while [ 0 ];
    do
        sleep 1
        docker exec -ti $DB_CONTAINER_ID bash -c "mysql -u root -proot --execute='SELECT 1'" > /dev/null 2>&1
        exit_code=$?
        if [[ $exit_code -eq 0 ]]; then
            break
        fi
    done
    tar xJf transfer/dump.sql.txz  -C transfer/
    docker exec -ti $DB_CONTAINER_ID sh -c "mysql -u root -proot domain < ./docker-entrypoint-initdb.d/dump.sql"
    rm -f transfer/dump.sql
}

usage () {
    echo "usage: start [[-s] | [-c] | [-h]]"
    echo "  -s | --start    Starts the docker containers only"
    echo "  -c | --create   Starts the docker containers and imports the database and sets up the project"
    echo "  -h | --help     Displays this help message"
}

while [ "$1" != "" ]; do
    case $1 in
        -s | --start )          startup
                                exit
                                ;;
        -c | --create )         create
                                exit
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done

usage
